package com.xtensus.hrmanagementapi.workflow;
import com.xtensus.hrmanagementapi.conge.demande.dto.CongeDemandeResponse;import com.xtensus.hrmanagementapi.conge.demande.exception.*;import com.xtensus.hrmanagementapi.domain.entity.*;import com.xtensus.hrmanagementapi.notificationfr.service.NotificationFrancaiseService;import com.xtensus.hrmanagementapi.repository.*;import java.time.LocalDateTime;import java.util.List;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;
@Service public class CongeWorkflowService{
 public record Anomalie(Long etapeId,Long demandeId,Integer priorite,String employe,String decideur){}
 private final PipelineValidationRepository pipelines;private final CongeDemandeWorkflowRepository workflows;private final CongeDemandeWorkflowEtapeRepository etapes;private final EmployeRepository employes;private final NotificationFrancaiseService notifications;private final EmailOutboxService emails;
 public CongeWorkflowService(PipelineValidationRepository p,CongeDemandeWorkflowRepository w,CongeDemandeWorkflowEtapeRepository e,EmployeRepository u,NotificationFrancaiseService n,EmailOutboxService m){pipelines=p;workflows=w;etapes=e;employes=u;notifications=n;emails=m;}
 @Transactional public void demarrer(CongeDemande d){PipelineValidation p=pipelines.findFirstByEmployeIdAndActifTrue(d.getEmploye().getId()).orElseThrow(()->new CongeDemandeInvalideException("Aucun circuit de validation actif n'est configuré pour cet employé"));List<PipelineValidationEtape> src=p.getEtapes().stream().filter(x->Boolean.TRUE.equals(x.getActif())).toList();if(src.isEmpty())throw new CongeDemandeInvalideException("Le circuit de validation ne contient aucune étape active");CongeDemandeWorkflow w=new CongeDemandeWorkflow();w.setDemande(d);w.setPipelineSource(p);w.setStatut("EN_COURS");w.setEtapeCourante(src.get(0).getPriorite());w.setDateCreation(LocalDateTime.now());for(var s:src){var x=new CongeDemandeWorkflowEtape();x.setWorkflow(w);x.setDecideur(s.getDecideur());x.setDecideurInitial(s.getDecideur());x.setPriorite(s.getPriorite());x.setStatut("EN_ATTENTE");w.getEtapes().add(x);}workflows.save(w);d.setDecideur(w.getEtapes().get(0).getDecideur());notifierAction(d,w.getEtapes().get(0));}
 @Transactional public boolean approuver(CongeDemande d,Long decideurId,String commentaire){var w=workflow(d);var c=courante(w,decideurId);c.setStatut("APPROUVEE");c.setCommentaire(commentaire);c.setDateAction(LocalDateTime.now());var suivante=w.getEtapes().stream().filter(x->x.getPriorite()>c.getPriorite()).findFirst().orElse(null);if(suivante!=null){w.setEtapeCourante(suivante.getPriorite());d.setDecideur(suivante.getDecideur());if(!Boolean.TRUE.equals(suivante.getDecideur().getActif())){suivante.setStatut("ANOMALIE");w.setStatut("ANOMALIE");notifierAnomalie(d,suivante);}else notifierAction(d,suivante);workflows.save(w);return false;}w.setStatut("APPROUVE");w.setEtapeCourante(null);w.setDateFin(LocalDateTime.now());workflows.save(w);return true;}
 @Transactional public void refuser(CongeDemande d,Long decideurId,String commentaire){var w=workflow(d);var c=courante(w,decideurId);c.setStatut("REFUSEE");c.setCommentaire(commentaire);c.setDateAction(LocalDateTime.now());w.getEtapes().stream().filter(x->x.getPriorite()>c.getPriorite()&&"EN_ATTENTE".equals(x.getStatut())).forEach(x->x.setStatut("ANNULEE"));w.setStatut("REFUSE");w.setEtapeCourante(null);w.setDateFin(LocalDateTime.now());workflows.save(w);}
 @Transactional public void annuler(CongeDemande d){workflows.findByDemandeId(d.getId()).ifPresent(w->{w.getEtapes().stream().filter(x->"EN_ATTENTE".equals(x.getStatut())).forEach(x->x.setStatut("ANNULEE"));w.setStatut("ANNULE");w.setEtapeCourante(null);w.setDateFin(LocalDateTime.now());workflows.save(w);});}
 @Transactional(readOnly=true) public void assurerModifiable(CongeDemande d){workflows.findByDemandeId(d.getId()).ifPresent(w->{if(w.getEtapes().stream().anyMatch(x->"APPROUVEE".equals(x.getStatut())))throw new CongeDemandeInvalideException("La demande ne peut plus être modifiée car une étape a déjà été approuvée");});}
 @Transactional(readOnly=true) public List<CongeDemande> demandesActives(Long id){return etapes.findByDecideurIdAndStatutOrderByWorkflowDemandeDateSoumissionDesc(id,"EN_ATTENTE").stream().filter(x->x.getPriorite().equals(x.getWorkflow().getEtapeCourante())).map(x->x.getWorkflow().getDemande()).toList();}
 @Transactional(readOnly=true) public List<Anomalie> anomalies(){return etapes.findByStatutOrderByWorkflowDemandeDateSoumissionDesc("ANOMALIE").stream().map(e->new Anomalie(e.getId(),e.getWorkflow().getDemande().getId(),e.getPriorite(),e.getWorkflow().getDemande().getEmploye().getPrenom()+" "+e.getWorkflow().getDemande().getEmploye().getNom(),e.getDecideur().getPrenom()+" "+e.getDecideur().getNom())).toList();}
 @Transactional public void reaffecter(Long etapeId,Long nouveauId,Long adminId){var e=etapes.findById(etapeId).orElseThrow(()->new IllegalArgumentException("Étape introuvable"));if(!"ANOMALIE".equals(e.getStatut()))throw new IllegalArgumentException("Seule une étape en anomalie peut être réaffectée");Employe n=employes.findById(nouveauId).orElseThrow(()->new IllegalArgumentException("Décideur introuvable"));if(!Boolean.TRUE.equals(n.getActif()))throw new IllegalArgumentException("Le nouveau décideur doit être actif");e.setDecideur(n);e.setReaffectePar(employes.findById(adminId).orElseThrow());e.setDateReaffectation(LocalDateTime.now());e.setStatut("EN_ATTENTE");e.getWorkflow().setStatut("EN_COURS");e.getWorkflow().getDemande().setDecideur(n);etapes.save(e);notifierAction(e.getWorkflow().getDemande(),e);}
 @Transactional(readOnly=true) public void enrichir(CongeDemandeResponse r){workflows.findByDemandeId(r.getId()).ifPresent(w->{var wr=new CongeDemandeResponse.WorkflowResume();wr.setStatut(w.getStatut());wr.setEtapeCourante(w.getEtapeCourante());wr.setEtapes(w.getEtapes().stream().map(this::dto).toList());r.setWorkflow(wr);});}
 private CongeDemandeResponse.EtapeWorkflowResume dto(CongeDemandeWorkflowEtape e){var x=new CongeDemandeResponse.EtapeWorkflowResume();x.setId(e.getId());x.setPriorite(e.getPriorite());x.setStatut(e.getStatut());x.setCommentaire(e.getCommentaire());x.setDateAction(e.getDateAction());var p=new CongeDemandeResponse.EmployeResume();p.setId(e.getDecideur().getId());p.setNom(e.getDecideur().getNom());p.setPrenom(e.getDecideur().getPrenom());p.setEmail(e.getDecideur().getEmail());x.setDecideur(p);return x;}
 private CongeDemandeWorkflow workflow(CongeDemande d){return workflows.findByDemandeId(d.getId()).orElseThrow(()->new DecisionCongeNonAutoriseeException("Aucun circuit de validation n'est associé à cette demande"));}
 private CongeDemandeWorkflowEtape courante(CongeDemandeWorkflow w,Long id){if(!"EN_COURS".equals(w.getStatut())||w.getEtapeCourante()==null)throw new DecisionCongeNonAutoriseeException("Ce circuit ne peut plus recevoir de décision");var e=etapes.findByWorkflowIdAndPriorite(w.getId(),w.getEtapeCourante()).orElseThrow();if(!e.getDecideur().getId().equals(id)||!"EN_ATTENTE".equals(e.getStatut()))throw new DecisionCongeNonAutoriseeException("Seul le décideur de l'étape active peut traiter cette demande");return e;}
 private void notifierAction(CongeDemande d,CongeDemandeWorkflowEtape e){String t="La demande de "+d.getEmploye().getPrenom()+" "+d.getEmploye().getNom()+" attend votre décision.";notifications.notifier(e.getDecideur(),"WORKFLOW_ACTION","Validation requise",t,"HAUTE",d.getId(),e.getId());emails.planifier(e.getDecideur(),"Action requise - demande de congé","Une décision vous attend",t);}
 private void notifierAnomalie(CongeDemande d,CongeDemandeWorkflowEtape e){for(Employe a:employes.findAll().stream().filter(x->"ADMIN".equalsIgnoreCase(x.getRole())&&Boolean.TRUE.equals(x.getActif())).toList()){String t="La demande #"+d.getId()+" est bloquée à l'étape "+e.getPriorite()+".";notifications.notifier(a,"WORKFLOW_ANOMALIE","Circuit bloqué",t,"HAUTE",d.getId(),e.getId());emails.planifier(a,"Circuit de validation bloqué","Réaffectation requise",t);}}
}
