import { DatePipe } from '@angular/common';
import { HttpClient } from '@angular/common/http';
import { Component, computed, inject, OnInit, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { environment } from '../../../environments/environment';
interface HistoryRow { id:number;demandeId:number;dateAction:string;action:string;commentaire:string|null;ancienStatut:string|null;nouveauStatut:string|null;employeId:number;employeNomComplet:string;typeDemande:string;typeConge:string;dateDebut:string;dateFin:string;heureDebut:string|null;heureFin:string|null;statutActuel:string; }
@Component({selector:'app-leave-history',imports:[FormsModule,DatePipe],templateUrl:'./leave-history.component.html',styleUrls:['../shared/resource-page.scss','./leave-history.component.scss']})
export class LeaveHistoryComponent implements OnInit {
 private readonly http=inject(HttpClient);private readonly url=`${environment.apiUrl}/conge-demande-historiques`;
 protected readonly rows=signal<HistoryRow[]>([]);protected readonly loading=signal(false);protected readonly error=signal<string|null>(null);protected readonly search=signal('');protected readonly employeeFilter=signal<number|null>(null);protected readonly editing=signal<HistoryRow|null>(null);protected readonly deleting=signal<HistoryRow|null>(null);protected readonly page=signal(1);protected readonly pageSize=signal(8);
 protected readonly employees=computed(()=>Array.from(new Map(this.rows().map(r=>[r.employeId,{id:r.employeId,name:r.employeNomComplet}])).values()).sort((a,b)=>a.name.localeCompare(b.name,'fr')));
 protected readonly filtered=computed(()=>{const q=this.search().trim().toLowerCase(),employee=this.employeeFilter();return this.rows().filter(r=>(employee===null||r.employeId===employee)&&(!q||[r.employeNomComplet,r.action,r.typeConge,r.statutActuel,String(r.demandeId)].some(v=>v.toLowerCase().includes(q))));});
 protected readonly totalPages=computed(()=>Math.max(1,Math.ceil(this.filtered().length/this.pageSize())));protected readonly pagedRows=computed(()=>{const start=(Math.min(this.page(),this.totalPages())-1)*this.pageSize();return this.filtered().slice(start,start+this.pageSize());});protected readonly pageStart=computed(()=>this.filtered().length?(Math.min(this.page(),this.totalPages())-1)*this.pageSize()+1:0);protected readonly pageEnd=computed(()=>Math.min(this.pageStart()+this.pageSize()-1,this.filtered().length));
 ngOnInit(){this.load();}protected load(){this.loading.set(true);this.http.get<HistoryRow[]>(this.url).subscribe({next:r=>{this.rows.set(r);this.page.set(1);this.loading.set(false);},error:()=>{this.error.set("L'historique n'a pas pu être chargé.");this.loading.set(false);}});}protected filtersChanged(){this.page.set(1);}protected changePageSize(v:number|string){this.pageSize.set(Number(v));this.page.set(1);}protected goToPage(v:number){this.page.set(Math.min(Math.max(v,1),this.totalPages()));}protected visiblePages(){const total=this.totalPages(),current=Math.min(this.page(),total),start=Math.max(1,Math.min(current-2,total-4));return Array.from({length:Math.min(5,total)},(_,i)=>start+i);}
 protected save(){const r=this.editing();if(!r)return;this.http.put<HistoryRow>(`${this.url}/${r.id}`,{action:r.action,commentaire:r.commentaire,ancienStatut:r.ancienStatut,nouveauStatut:r.nouveauStatut}).subscribe({next:()=>{this.editing.set(null);this.load();},error:()=>this.error.set("La modification n'a pas pu être enregistrée.")});}protected remove(){const r=this.deleting();if(!r)return;this.http.delete(`${this.url}/${r.id}`).subscribe({next:()=>{this.deleting.set(null);this.load();},error:()=>this.error.set("La ligne n'a pas pu être supprimée.")});}protected clone(r:HistoryRow){return {...r};}protected nature(v:string){return v==='AUTORISATION_ABSENCE'?"Autorisation d'absence":'Congé';}
}
