import {Component,computed,inject,OnInit,signal} from '@angular/core';import {FormsModule} from '@angular/forms';import {forkJoin} from 'rxjs';import {UserService} from '../users/services/user.service';import {UserResponse} from '../users/models/user.model';import {PipelinePayload,ValidationPipeline,ValidationPipelineService,WorkflowAnomaly} from './validation-pipeline.service';import {AppIconComponent} from '../../shared/components/app-icon/app-icon.component';
@Component({selector:'app-validation-pipelines',imports:[AppIconComponent,FormsModule],templateUrl:'./validation-pipelines.component.html',styleUrls:['../shared/resource-page.scss','./validation-pipelines.component.scss']})export class ValidationPipelinesComponent implements OnInit{
 protected anomalies=signal<WorkflowAnomaly[]>([]);
 private api=inject(ValidationPipelineService);private usersApi=inject(UserService);protected pipelines=signal<ValidationPipeline[]>([]);protected users=signal<UserResponse[]>([]);protected search=signal('');protected editing=signal<ValidationPipeline|null>(null);protected open=signal(false);protected error=signal<string|null>(null);protected message=signal<string|null>(null);protected name='';protected employeeId:number|null=null;protected active=true;protected steps:{decideurId:number|null}[]=[];
 protected filtered=computed(()=>{const q=this.search().toLowerCase();return this.pipelines().filter(p=>(p.nom+' '+p.employe.prenom+' '+p.employe.nom).toLowerCase().includes(q))});protected employees=computed(()=>this.users().filter(u=>u.role==='EMPLOYEE'&&u.enabled));protected approvers=computed(()=>this.users().filter(u=>u.enabled&&['DG','DT','HR','ADMIN'].includes(u.role)));
 protected activeCount=computed(()=>this.pipelines().filter(p=>p.actif).length);protected stepCount=computed(()=>this.pipelines().reduce((total,p)=>total+p.etapes.length,0));
 protected roleLabel(role:string){return({DG:'Directeur général',DT:'Directeur technique',HR:'Ressources humaines',ADMIN:'Administrateur',EMPLOYEE:'Employé'} as Record<string,string>)[role]??role;}
 protected approversFor(index:number):UserResponse[]{const selected=new Set(this.steps.map((step,i)=>i===index?null:step.decideurId).filter((id):id is number=>id!==null));return this.approvers().filter(user=>!selected.has(user.id));}
 ngOnInit(){this.load()}protected load(){forkJoin({pipelines:this.api.findAll(),anomalies:this.api.findAnomalies(),users:this.usersApi.findAll()}).subscribe({next:r=>{this.pipelines.set(r.pipelines);this.anomalies.set(r.anomalies);this.users.set(r.users)},error:e=>this.error.set(e?.error?.message??'Impossible de charger les circuits de validation.')})}
 protected create(){this.editing.set(null);this.name='';this.employeeId=null;this.active=true;this.steps=[{decideurId:null}];this.open.set(true)}protected edit(p:ValidationPipeline){this.editing.set(p);this.name=p.nom;this.employeeId=p.employe.id;this.active=p.actif;this.steps=p.etapes.map(e=>({decideurId:e.decideur.id}));this.open.set(true)}protected addStep(){this.steps.push({decideurId:null})}protected removeStep(i:number){if(this.steps.length>1)this.steps.splice(i,1)}protected move(i:number,d:number){const j=i+d;if(j<0||j>=this.steps.length)return;[this.steps[i],this.steps[j]]=[this.steps[j],this.steps[i]]}
 protected save(){this.error.set(null);if(!this.name.trim()||!this.employeeId||this.steps.some(s=>!s.decideurId)){this.error.set('Complétez le nom, l’employé et chaque décideur.');return}const payload:PipelinePayload={nom:this.name.trim(),employeId:this.employeeId,actif:this.active,etapes:this.steps.map((s,i)=>({decideurId:s.decideurId!,priorite:i+1}))};const op=this.editing()?this.api.update(this.editing()!.id,payload):this.api.create(payload);op.subscribe({next:()=>{this.open.set(false);this.message.set('Circuit enregistré avec succès.');this.load()},error:e=>this.error.set(e?.error?.message??'Impossible d’enregistrer le circuit.')})}
 protected disable(p:ValidationPipeline){if(!confirm(`Désactiver le circuit « ${p.nom} » ?`))return;this.api.disable(p.id).subscribe({next:()=>{this.message.set('Circuit désactivé.');this.load()},error:e=>this.error.set(e?.error?.message??'Impossible de désactiver le circuit.')})}protected person(id:number|null){const u=this.users().find(x=>x.id===id);return u?`${u.firstName} ${u.lastName}`:'Étape non définie'}
 protected reassign(a:WorkflowAnomaly,value:string){const id=Number(value);if(!id)return;this.api.reassign(a.etapeId,id).subscribe({next:()=>{this.message.set('Étape réaffectée avec succès.');this.load()},error:e=>this.error.set(e?.error?.message??'Impossible de réaffecter cette étape.')})}
}
